export { default as erase } from "./erase.png"
export { default as undo } from "./undo.png"
export { default as redo } from "./redo.png"
export { default as thin } from "./thin.png"
export { default as thick } from "./thick.png"
export { default as help } from "./help.png"
export { default as exit } from "./exit.png"